### ISSUE TITLE
Consider pub use psl

### ISSUE THREAD

**Issue by rusty-snake** [addr-rs/addr#11]
```rust
#[cfg(psl)]
pub use psl;
// or
#[cfg(psl)]
pub use psl::List;
```

This would allow to use the example from the README w/o adding an additional crate to use this crate.

**Comment by rushmorem** [comment]
I wanted to make it clear that users can use whatever implementation of the `psl_types::List` they wanted. But you are right, `psl` makes for a nice default since it requires no further setup and it is the fastest. Also considering the typical use case for users of a crate like this (parsing domain names and email addresses), I would guess most can do just fine with a static list. Those who need a dynamic list can pull in `publicsuffix::List` instead.
